
num_classes: 72
label_map: { 
   1: "Bicycles_Only",
   2: "Bumpy_Road",
   3: "Buses_Priority",
   4: "Centre_Line",
   5: "Closed_To_Pedestrians",
   6: "Crossroads",
   7: "Dangerous_Wind _Gusts",
   8: "Directions_Indicator",
   9: "Falling_Rocks",
  10: "Keep_Left",
  11: "Keep_Right",
  12: "Left_Lane_Ends",
  13: "Maximum_Height_in_Meters",
  14: "Maximum_Weight_in_Tons",
  15: "Maximum_Width_in_Meters",
  16: "Minimum_Speed_Limit_50km",
  17: "Motor_Vehicles_Only",
  18: "No_Bicycles",
  19: "No_Buses",
  20: "No_Entry",
  21: "No_Motorcycles_Or_Mopeds",
  22: "No_Motor_Vehicles",
  23: "No_Motor_Vehicles_Except_Motorcycles_And_Mopeds",
  24: "No_Nonmotorized_Vehicle",
  25: "No_Overtaking",
  26: "No_Parking",
  27: "No_Pedestrian_Crossing",
  28: "No_Right_Turn_Crossing",
  29: "No_Stopping",
  30: "No_Trucks",
  31: "No_Turns",
  32: "No_TwoPerson_Motorcycles",
  33: "No_TwoStage_Right_Turn_For_Mopeds",
  34: "No_UTurn",
  35: "No_Vehicles_Carrying_Dangerous_Goods",
  36: "OneWay",
  37: "OneWay_To_The_Left",
  38: "OneWay_To_The_Right",
  39: "Other_Dangers",
  40: "Pedestrians_Only",
  41: "Pedestrian_Crossing",
  42: "RailroadCrossing",
  43: "Roadworks",
  44: "Road_Closed_To_Pedestrian",
  45: "Road_Closed_To_Vehicles",
  46: "Road_Narrows",
  47: "Rotary",
  48: "Roundabout",
  49: "Safety_Zone",
  50: "School_Crossing",
  51: "School_Zone",
  52: "Slippery_Surface",
  53: "Slow_Down",
  54: "Sound_Horn",
  55: "Speed_Limit_90km",
  56: "Steep_Ascent_10%",
  57: "Steep_Descent_10%",
  58: "Stop",
  59: "Stop_Line",
  60: "Straight_Ahead_Or_Left_Turn",
  61: "Straight_Ahead_Or_Right_Turn",
  62: "Succession_Of_More_Than_Two_Curves_To_The_Right",
  63: "Traffic_Lights_Ahead",
  64: "Traffic_Merges_From_Left",
  65: "Turn_Left",
  66: "Turn_Left_Or_Right",
  67: "Turn_Right",
  68: "TwoStage_Right_Turn_For_Mopeds",
  69: "TwoWay_Traffic_Ahead",
  70: "Wild_Animals_Crossing",
  71: "Traffic_Circle",
}

input_rand_hflip: true
jitter_min: 0.8
jitter_max: 1.2
learning_rate: 0.001
image_size: 224
